#ifndef __INSTRUCTIONS_H__
#define __INSTRUCTIONS_H__

#include <stdint.h>

typedef uint8_t instr;

#define INSTR_DROP1 0
#define INSTR_DROP2 1
#define INSTR_DROP3 2
#define INSTR_DROPN 3
#define INSTR_DUP1 4
#define INSTR_DUP2 5
#define INSTR_DUP3 6
#define INSTR_DUPN 7
#define INSTR_OVER 8
#define INSTR_PICK 9
#define INSTR_ROTL 10
#define INSTR_ROTR 11
#define INSTR_SWAP 12
#define INSTR_ADD 32
#define INSTR_SUB 33
#define INSTR_MUL 34
#define INSTR_DIV 35
#define INSTR_PUSH1_INT 96
#define INSTR_PUSH2_INT 97
#define INSTR_PUSH3_INT 98
#define INSTR_PUSHN_INT 99
#define INSTR_PUSH1_FLOAT 100
#define INSTR_PUSH2_FLOAT 101
#define INSTR_PUSH3_FLOAT 102
#define INSTR_PUSHN_FLOAT 103
#define INSTR_PUSH1_QUOTE 104
#define INSTR_PUSH2_QUOTE 105
#define INSTR_PUSH3_QUOTE 106
#define INSTR_PUSHN_QUOTE 107
#define INSTR_PUSH1_QREF 108
#define INSTR_PUSH2_QREF 109
#define INSTR_PUSH3_QREF 110
#define INSTR_PUSHN_QREF 111
#define INSTR_CALL 128
#define INSTR_KEEP1 129
#define INSTR_KEEP2 130
#define INSTR_KEEP3 131
#define INSTR_IF 160

#endif
